version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wordai
      POSTGRES_USER: wordai_user
      POSTGRES_PASSWORD: wordai_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wordai_user -d wordai"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://wordai_user:wordai_password@db:5432/wordai
      - POSTGRES_DB=wordai
      - POSTGRES_USER=wordai_user
      - POSTGRES_PASSWORD=wordai_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./ssl:/app/ssl
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver_plus 0.0.0.0:8000 --cert-file /app/ssl/localhost+2.pem --key-file /app/ssl/localhost+2-key.pem"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./ssl:/app/ssl
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend

volumes:
  postgres_data: 