# Generated by Django 5.2.3 on 2025-06-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_pipeline', '0001_initial'),
        ('template_engine', '0005_delete_templatecontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='template_engine.template'),
        ),
    ]
