# Generated by Django 5.2.3 on 2025-06-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
