# Generated by Django 5.2.3 on 2025-06-21 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_engine', '0002_document_alter_template_id_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_templates', to='template_engine.document')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_documents', to='template_engine.template')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('template', 'context_document')},
            },
        ),
    ]
