# Generated by Django 5.2.3 on 2025-06-21 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('template_engine', '0003_templatecontext'),
        ('rag_pipeline', '0001_initial'),
    ]

    operations = [
        # Remove the duplicated Document and DocumentChunk models
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
        # Update TemplateContext to reference RAG pipeline Document
        migrations.AlterField(
            model_name='templatecontext',
            name='context_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_templates', to='rag_pipeline.document'),
        ),
    ]
