# Generated by Django 5.2.3 on 2025-06-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_engine', '0004_auto_20250621_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateContext',
        ),
    ]
